/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "- 1 New celestial.": "- 1 新天体。",
    "Total Time": "总时长",
    "Total": "总计",
    "Track Ores!": "跟踪矿石!",
    "Trophy Room": "奖杯室",
    "Tree of Life Levels:": "生命之树等级:",
    "Undersea Eviscerator": "海底切割器",
    "Yin-Yang: Mine in World 2 with the Key equipped.": "阴阳:在装备了钥匙的情况下，世界2中的矿井。",
    "You appear to be new to this game, would you like to see how to play? The information can be viewed at any time by selecting 'FAQ' in the menu.": "你似乎对这个游戏很陌生，你想看看怎么玩吗?您可以随时在菜单中选择“FAQ”查看相关信息。",
    "You can either hold W, A, S, D to manually move in that direction, press the buttons with 1 arrow to move 1 block in that direction, press any of the arrow keys to automine in that direction, or press the buttons with 3 arrows to automine in that direction.": "你可以按住W, A, S, D手动朝那个方向移动，按下带有1个箭头的按钮朝那个方向移动一个方块，按下任意方向键自动朝那个方向移动，或者按下带有3个箭头的按钮自动朝那个方向移动。",
    "You can get: ->": "你可以得到: ->",
    "World One": "世界 1",
    "World Two": "世界 2",
    "What are variants?": "什么是变体?",
    "Webhook Settings": "Webhook设置",
    "Preview": "预览",
    "Quantum Entangler": "量子纠缠器",
    "Play!": "开始！",
    "Pickaxes": "镐子",
    "Powerups": "通电",
    "Player Statistics": "玩家统计",
    "Planet Buster": "星球爆炸",
    "Ore Index": "矿石指标",
    "Ore Fissions!": "矿石裂变！",
    "Ore Crafts!": "矿石工艺品！",
    "Ore Logs": "矿石日志",
    "Ore Tiers": "矿石层级",
    "Ore Tracker": "矿石跟踪器",
    "Other Questions": "其他问题",
    "Paradoxical Progression": "矛盾进程",
    "Paradoxical Progression will give access to the next level instead of a random item.": "矛盾进程将让玩家进入下一个关卡，而不是随机道具。",
    "Pickaxe consistency is the average amount of blocks you would be mining per block mined. It is calculated with the formula: (revealed * luck / proc)": "镐子一致性是指你将开采的每个区块的平均数量。其计算公式为:(显示 * 幸运 / 产量)",
    "Automatically cycles through powerups and activates them if they are ready. -25% cooldown time, +50% activation time.": "自动循环通电，并在通电准备就绪时激活它们-25%的冷却时间，+50%的激活时间。",
    "Blocks Mined": "已开采的区块",
    "Capacity": "容量",
    "Something after Coronary Catastrophe...": "冠状动脉灾难之后…",
    "One thing you have to pay attention to is spawn sounds. Rare ores all have a noise to indicate they have been spawned in the mine, and it is generally recommended to always collect these ores.": "你需要注意的一件事是产生声音。稀有矿石都有噪音，表明他们已经在矿山中产卵，一般建议总是收集这些矿石。",
    "Crafting is the most important part of the game. It allows you to create better pickaxes and make gears that will help you progress. New pickaxes will either let you mine more blocks through abilities or gain more luck. Gears are just like upgrades in other games and can increase luck, speed, and other silly things that will help with progression.": "锻造是游戏中最重要的部分。它可以让你创造更好的镐和装备，这将有助于你的进步。新的镐子可以让你通过技能挖掘更多方块或获得更多运气。装备就像其他游戏中的升级一样，可以增加运气、速度和其他有助于进程的东西。",
    "Create!": "创造!",
    "Craft": "制作",
    "Back to Game": "返回游戏",
    "Audio Settings": "音频设置",
    "Automine Protection": "自动保护",
    "Allows you to access the ore tracker menu, pointing you towards the nearest rare ore that had a spawn message with it owned.": "允许你访问矿石跟踪菜单，指向你最近的稀有矿石，有一个产生消息与它拥有。",
    "Artifice Annihilator": "神兵歼灭者",
    "Cave Types": "洞穴类型",
    "Cave": "洞穴",
    "Caves Generated": "生成的洞穴",
    "Cloud Layer": "云层",
    "Events": "活动",
    "Enables cave spawns in World 2 and moderately increases cave size.": "允许在世界2中生成洞穴，并适度增加洞穴大小。",
    "Enables the spawn of Abysstone Caves.": "启用深渊石窟的生成。",
    "Equip!": "装备!",
    "Menu": "菜单",
    "How do I play?": "玩法？",
    "Gives you any unowned pickaxe or gear for at least 1 minute. Will not give World 1 pickaxes in World 2, and is disabled in Subworld 1. The given item is wiped on refresh.": "给你任意无主的镐子或工具至少1分钟。在世界2中不会给世界1的鹤嘴锄，在子世界1中被禁用。给定的物品在刷新时被擦除。",
    "Haste II Beacon": "急速 II 信标",
    "Hyperdrive Accelerator": "超光速加速器",
    "It doesn't appear like you have a name yet! Pick one out for yourself!": "你好像还没有名字啊!为你自己挑一个吧!",
    "(Make sure your name is appropriate as it will appear when you generate ore logs)": "(确保你的名字是合适的，因为它会在你生成日志时出现)",
    "Confirm!": "确认!",
    "Cave types have a chance of generating when a cave is generated. These have special blocks instead of the normal layer, and have their own loot tables. These loot tables contain cave exclusives, which can only be generated in that specific cave type and are not affected by any luck as of now. Any cave exclusive will log, no matter the rarity.": "当洞穴生成时，洞穴类型有一定几率生成。这些有特殊的块而不是普通的层，并有自己的战利品表。这些战利品表包含洞穴专属，只能在特定的洞穴类型中生成，并且目前不受任何运气的影响。任何洞穴都是独一无二的，无论多么稀有。",
    "Caves generate in the mine at a rate of 1/500 after crafting Geode Staff. They will mine a little over 1,500 blocks and will give you whatever was mined. They don't increase blocks mined.": "在制作水晶杖后，洞穴以1/500的速度在矿井中生成。他们将开采超过1500个区块，然后把挖到的都给你。它们不会增加开采的区块。",
    "Currently, this will allow miners to obtain ores from World 1 that spawn in caves, this will be a thing until new cave types are made for World 2.": "目前，这将允许矿工从世界1中获得在洞穴中产生的矿石，这将是一个事情，直到新的洞穴类型为世界2。",
    "Draws from past creations and through corruption, magnifies it fivefold.": "从过去的创造中吸取，通过腐败，将其放大五倍。",
    "- 2 New World 2 gears": "- 2 新世界2装备",
    "- 2 New Gears!": "- 2 新装备!",
    "- 2 new ore tiers": "- 2 新矿石层级",
    "- 9 New event ores found in a few World 1 layers.": "- 9个新的活动矿石会在部分世界1层中发现",
    "- Changed a few powerup effects.": "- 改变了一些通电效果。",
    "- A few QOL changes with crafting.": "- 一些关于锻造的QOL改变。",
    "- Overhauled Powerup UI.": "- 升级通电UI。",
    "- Let me know if progression needs any more tweaking and I'll try to make it better.": "- 让我知道进程是否需要更多的调整，我会努力让它变得更好。",
    "Events:": "活动:",
    "Export Data": "导出存档",
    "Fission": "裂变",
    "Flawless": "完美无瑕",
    "Flawless :": "完美无瑕:",
    "Fortune III Book": "财富 III 书",
    "Game Settings": "游戏设置",
    "Gears": "装备",
    "Generate Ore Logs": "生成矿石日志",
    "Has x luck.": "拥有 x 幸运.",
    "High Powered Vacuum": "大功率真空",
    "How do i find [layer]? (and other secrets)": "我如何找到[层]? (以及其他秘密)",
    "How to use: Click on an ore in a variant inventory, or manually input the information!": "使用方法:点击一个变体库存中的矿石，或者手动输入信息!",
    "I think there's something new for you to check out in the Portal Room, you should head on over there!": "我觉得传送室里有新的东西给你看，你应该去那里看看!",
    "Exponential Centrifuge": "指数离心机",
    "Every pigment of color swirls up from below, surrounding you in an eternal rainbow...": "每一种颜色都从下面盘旋而上，在你周围形成一道永恒的彩虹……",
    "Disguised Chills": "伪装的寒意",
    "Dimensional Update": "维度更新",
    "..This is where it ends? The most powerful tool in all the worlds..? No.. it can't end here there must be something more...": "..这就是结束的地方?世界上最强大的工具…?没有. .事情不会就此结束，一定还有别的事情……",
    "The Key to World 2.": "世界2的钥匙。",
    "The Key": "钥匙",
    "The locations tab provides some very helpful areas. The first one is the forge, which allows you to craft certain ores you might need, or fission rare ores you have into a bunch of more common ores. The second is variant conversion, which can be more easily accessed by clicking on an ore in your inventory that is a variant. It will allow you to convert these variants into their normal selves, gaining more the rarer the variant. The third location is the workshop, which is currently only visible in Subrealm 1. The workshop will allow you to upgrade certain items, making them work better than usual.": "位置选项卡提供了一些非常有用的区域。第一个是锻造，它允许你制造你可能需要的某些矿石，或者将你拥有的稀有矿石裂变成一堆更常见的矿石。第二种是变体转换，你可以通过点击库存中的变体矿石来更轻松地访问它。它将允许你将这些变体转换成它们的正常自我，越稀有的变体获得越多。第三个位置是车间，目前只在子领域1中可见。车间将允许您升级某些物品，使它们比平时更好地工作。",
    "The logs tab is where you can generate ore logs for your current session. This only logs Flawless tier and above ores, along with any rare cave ores. These are also how you can provide proof of ores in the Discord.": "在 日志 选项卡中，您可以为当前会话生成 矿石日志。这只记录完美层和以上的矿石，以及任何稀有的洞穴矿石。这些也是你在Discord中提供矿石证明的方式。",
    "The Menu": "菜单",
    "The menu contains a lot of important tabs that you should make note of!": "菜单包含很多重要的标签，你应该注意!",
    "The main pickaxe of Subrealm 1.": "子领域1的主要 镐子。",
    "Offline Progression": "离线进度",
    "Pickaxe: Mine down into the barrier to have a chance to obtain it": "镐子:挖到障碍物有机会获得它",
    "Please Login to Galaxy for Cloud autosave.": "请登入Galaxy进行云端自动储存。",
    "Potentiality Multiplier": "潜能乘数",
    "Powerups And Other Things Like Them": "升级道具和其他类似的东西",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Duration: ": "持续时长: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "ms Mining Speed.": "ms 采矿速度.",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\- New(.+)$/,
    /^\- Bug(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.,]+)\*$/,
    /^([\d\.]+)\/([\d\.]+)T\*$/,
    /^([\d\.]+)\/([\d\.]+)Qn\*$/,
    /^([\d\.]+)\/([\d\.]+)qd\*$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.]+)T$/,
    /^([\d\.]+)\/([\d\.]+)Qn$/,
    /^([\d\.]+)\/([\d\.]+)qd$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Has an ability proc rate of (.+).$/, '能力触发率为 $1。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Has ([\d\.]+)x luck.$/, '拥有 $1x 幸运。'],
    [/^\+([\d\.]+)x Luck.$/, '\+$1x 幸运。'],
    [/^\+([\d\.]+)x Base Luck.$/, '\+$1x 基础幸运。'],
    [/^\+([\d\.]+)\% ability activation rate.$/, '\+$1x 能力激活率。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Blocks Mined$/, '$1 已开采地块'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Event([\d\.,]+):$/, '活动 $1:'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Main Effect\(s\): (.+) boost on (.+)$/, '主效果：$1 提升到 $2'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Rate: (.+) every (.+)ms$/, '速率：$1 每 $2ms'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);